2023-07-06 21:41:08,569 - root - INFO - init user 1-run
2023-07-06 21:41:08,569 - root - INFO - user 1 submits-run
2023-07-06 21:41:08,569 - root - INFO - init user 2-run
2023-07-06 21:41:08,569 - root - INFO - user 2 submits-run
2023-07-06 21:41:08,569 - root - INFO - init user 3-run
2023-07-06 21:41:08,569 - root - INFO - user 3 submits-run
2023-07-06 21:41:08,571 - root - INFO - init user 4-run
2023-07-06 21:41:08,571 - root - INFO - user 4 submits-run
2023-07-06 21:41:08,571 - root - INFO - init processor-run
2023-07-06 21:41:08,571 - root - INFO - init gpt-run
2023-07-06 21:41:10,580 - root - INFO - user 2 submits-run
2023-07-06 21:41:10,580 - root - INFO - user 4 submits-run
2023-07-06 21:41:10,580 - root - INFO - user 1 submits-run
2023-07-06 21:41:10,580 - root - INFO - user 3 submits-run
2023-07-06 21:41:12,595 - root - INFO - user 1 submits-run
2023-07-06 21:41:12,595 - root - INFO - user 2 submits-run
2023-07-06 21:41:12,595 - root - INFO - user 3 submits-run
2023-07-06 21:41:12,595 - root - INFO - user 4 submits-run
2023-07-06 21:41:14,602 - root - INFO - user 3 submits-run
2023-07-06 21:41:14,602 - root - INFO - user 4 submits-run
2023-07-06 21:42:10,376 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:42:14,876 - root - INFO - user 1 receives-run
2023-07-06 21:42:34,964 - root - INFO - user 2 receives-run
2023-07-06 21:43:41,075 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:43:45,224 - root - INFO - user 3 receives-run
2023-07-06 21:44:44,524 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:45:19,561 - root - INFO - user 4 receives-run
2023-07-06 21:45:41,641 - root - INFO - user 2 receives-run
2023-07-06 21:46:03,740 - root - INFO - user 4 receives-run
2023-07-06 21:46:54,461 - root - ERROR - The server is overloaded or not ready yet.-exception_process
2023-07-06 21:46:57,957 - root - INFO - user 1 receives-run
2023-07-06 21:47:47,439 - root - ERROR - The server is overloaded or not ready yet.-exception_process
2023-07-06 21:47:50,162 - root - INFO - user 3 receives-run
2023-07-06 21:48:49,140 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:49:00,467 - root - INFO - user 1 receives-run
2023-07-06 21:49:30,581 - root - INFO - user 2 receives-run
2023-07-06 21:49:50,669 - root - INFO - user 3 receives-run
2023-07-06 21:50:16,751 - root - INFO - user 4 receives-run
2023-07-06 21:51:15,065 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:51:21,048 - root - INFO - user 3 receives-run
2023-07-06 21:51:59,323 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:53:03,812 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /v1/chat/completions-urlopen
2023-07-06 21:53:09,484 - root - INFO - user 4 receives-run
